name: "Deploy mycr"

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - .github/workflows/argonaut-preprod-mycr.yaml
      - Dockerfile
      - .art/argonaut-preprod-preprod-mycr.yaml
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:



jobs:
  build:
    
    environment: 
      name: preprod 
    
    runs-on: ubuntu-latest
    name: Build and Push Img
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Fetch repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Get Short SHA
        id: get_sha
        run: echo ::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download art
        run: |
          curl --silent https://github.com/argonautdev/public/releases/latest/download/art-linux -L -o art
          chmod +x ./art
          mv ./art /usr/local/bin/art
      - name: Fetch BuildTime Secrets
        run: |
          art configure --key ${{ secrets.argonautdev_ART_KEY }} --secret ${{ secrets.argonautdev_ART_SECRET }}
          art app envvars get -f .art/argonaut-preprod-preprod-mycr.yaml \
            --set appName="mycr" \
            --set argonaut.env="preprod" \
            --set argonaut.region="us-east-2" \
            --set argonaut.cluster="preprod" \
            --set argonaut.serviceType="stateless" \
            --set argonaut.imageRegistry="dockerhub" \
            --type buildtime \
            --format dotenv > art-build-secrets.env
          echo 'ART_BUILD_SECRETS_FILE<<EOF' >> $GITHUB_ENV
          cat art-build-secrets.env >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Login to Github container repo
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: argonauthub
          password: ${{ secrets.ARG_DOCKERHUB_ACCESS_TOKEN }}
      - name: Build Image and Push
        uses: docker/build-push-action@v2
        id: build-push
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            ${{ env.ART_BUILD_SECRETS_FILE }}
          tags: docker.io/argonauthub/mycr-preprod:${{ steps.get_sha.outputs.SHA_SHORT }}
          cache-from: type=registry,ref=docker.io/argonauthub/mycr-preprod:buildcache
          cache-to: type=registry,ref=docker.io/argonauthub/mycr-preprod:buildcache,mode=max

  deploy:
    
    environment: 
      name: preprod 
    
    runs-on: ubuntu-latest
    name: Deploy to Argonaut
    needs: build
    steps:
      - name: Fetch repo
        uses: actions/checkout@v2
      - name: Fetch branch name
        shell: bash
        run: echo ::set-output name=BRANCH_NAME::${GITHUB_REF#refs/heads/}
        id: get_branch_name
      - name: Get Short SHA
        id: get_sha
        run: echo ::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)
      - name: Download art
        run: curl --silent https://github.com/argonautdev/public/releases/latest/download/art-linux -L -o art
      - name: Configure art
        run: |
          chmod +x ./art
          sudo mv ./art /usr/local/bin/art
          art configure --key ${{ secrets.argonautdev_ART_KEY }} --secret ${{ secrets.argonautdev_ART_SECRET }}
          art app deploy -f .art/argonaut-preprod-preprod-mycr.yaml \
            --set image="docker.io/argonauthub/mycr-preprod" \
            --set 'labels.argonaut\.dev/git-provider'='github' \
            --set argonaut.git-provider='github' \
            --set imageTag="${{ steps.get_sha.outputs.SHA_SHORT }}" \
            --set appName="mycr" \
            --set argonaut.env="preprod" \
            --set argonaut.region="us-east-2" \
            --set argonaut.cluster="preprod" \
            --set argonaut.serviceType="stateless" \
            --set argonaut.imageRegistry="dockerhub" 