name: "Delete corresponding App on branch delete"

on:
  delete:
  workflow_dispatch:

jobs:
  delete:
    environment:
      name: dev3

    runs-on: ubuntu-latest
    name: Deleting App
    steps:
      - name: Fetch Repo
        uses: actions/checkout@v2
      - name: Branch Deleted
        run: echo "${{ github.event.ref }}"
      - name: Default Branch
        run: echo "${{ github.event.repository.default_branch }}"
      - name: Download art
        run: curl --silent https://github.com/argonautdev/public/releases/latest/download/art-linux -L -o art
      - name: Configure art
        run: |
          chmod +x ./art
          sudo mv ./art /usr/local/bin/art
          art configure --key ${{ secrets.dev_ART_KEY }} --secret ${{ secrets.dev_ART_SECRET }}
          art app delete -f .art/argonaut-dev3-wahal-appdeletetest.yaml --set appName=${{ (github.event.ref == github.event.repository.default_branch) && 'appdeletetest' || format('{0}-{1}', 'appdeletetest', github.event.ref) }}
          
      - name: Delete workflow files
        run: |
          rm .art/argonaut-dev3-wahal-appdeletetest.yaml .github/workflows/argonaut-dev3-appdeletetest.yaml ./.github/workflows/argonaut-dev3-appdeletetest-delete.yaml
          git add .
          git commit -m "delete argonaut workflow files"
          git push
