name: Display information about GitHub Actions CPU architecture
on: push
jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
        number:
          [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
          ]

    name: Display lscpu - ${{matrix.number}}
    runs-on: ${{matrix.runs-on}}
    steps:
      - name: Run lscpu
        run: lscpu
