on:
  workflow_dispatch:

jobs:
  tests:
    runs-on:
      - namespace-profile-ankit-test
    strategy:
      matrix: 
        a: [1,2,3,4,5,6,7,8,9,10]
        b: [1,2,3]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup npm cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            ~/.npm
            ./node_modules
      - name: Install dependencies
        run: npm install
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
